services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronos-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cronos-network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: cronos-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cronos-network
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    container_name: cronos-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cronos_api
      POSTGRES_USER: cronos
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cronos-network
    mem_limit: 1024m

  redis:
    image: redis:7-alpine
    container_name: cronos-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cronos-network
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru

networks:
  cronos-network:
    driver: bridge